global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.10.10:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: [
                    '192.168.10.10:9100',
                    '192.168.10.11:9100',
                    '192.168.10.12:9100'
                  ]
  
  # Create a job for cadvisor.
  - job_name: 'cadvisor'
    static_configs:
      - targets: [
                    '192.168.10.10:18080',
                    '192.168.10.11:18080',
                    '192.168.10.12:18080'
                  ]
    
    

  # Create a job for Docker daemons.
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
    

