---
- hosts: all 
  pre_tasks:
  
    - name: installa dependency
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
  
  tasks:
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
    - name: restart docker
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
        dest:  /usr/local/bin/docker-compose
        mode: '0755'
      become: true